  hostNODE_NAME:
    container_name: hostNODE_NAME
    image: parity/parity:v1.9.5
    networks:
    - my-swarm-network
    volumes:
    - ./deployment/chain/spec.json:/parity/spec.json:ro
    - ./deployment/chain/reserved_peers:/parity/reserved_peers:ro
    - ./deployment/NODE_NAME/password:/parity/password:ro
    - ./deployment/NODE_NAME/authority.toml:/parity/authority.toml:ro
    - ./deployment/NODE_NAME/${NETWORK_NAME}:/parity/data/keys/${NETWORK_NAME}
    - ./data/NODE_NAME:/parity/data
    command: --chain /parity/spec.json --config /parity/authority.toml -d /parity/data
  ipfs_host:
    container_name: ipfs_host
    ports:
    - 4001:4001
    - 8080:8080
    - 5001:5001
    image: ipfs/go-ipfs:latest
    networks:
    - my-swarm-network
    volumes:
    - ./ipfs/staging:/export
    - ./ipfs/data:/data/ipfs
networks:
  my-swarm-network:
    external: true
